export const blogCategories = [
  { value: 'adobe-commerce', label: 'Adobe Commerce' },
  { value: 'adobe-photoshop', label: 'Adobe Photoshop' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'ai', label: 'Artificial Intelligence' },
  { value: 'ai-news', label: 'AI News' },
  { value: 'aiw', label: 'AIW' },
  { value: 'angular', label: 'Angular' },
  { value: 'app-development', label: 'App Development' },
  { value: 'app-website-statistics', label: 'App/Website Statistics' },
  { value: 'astrology', label: 'Astrology' },
  { value: 'automotive-app-development', label: 'Automotive App Development' },
  { value: 'blockchain', label: 'Blockchain' },
  { value: 'car-service', label: 'Car Service' },
  { value: 'dating', label: 'Dating' },
  { value: 'devops', label: 'DevOps' },
  { value: 'drupal', label: 'Drupal' },
  { value: 'e-commerce', label: 'E-commerce' },
  { value: 'education', label: 'Education' },
  { value: 'entertainment-media', label: 'Entertainment & Media' },
  { value: 'fintech', label: 'Fintech' },
  { value: 'fitness', label: 'Fitness' },
  { value: 'flutter', label: 'Flutter' },
  { value: 'flutter-developer', label: 'Flutter Developer' },
  { value: 'flutterflow', label: 'FlutterFlow' },
  { value: 'food-delivery-app', label: 'Food Delivery App' },
  { value: 'health-care', label: 'Health care' },
  { value: 'hire-developers', label: 'Hire Developers' },
  { value: 'hiring-guide', label: 'Hiring Guide' },
  { value: 'ionic', label: 'Ionic' },
  { value: 'iphone', label: 'iPhone' },
  { value: 'laundry', label: 'Laundry' },
  { value: 'logistics', label: 'Logistics' },
  { value: 'magento', label: 'Magento' },
  { value: 'next-js', label: 'Next JS' },
  { value: 'node-js', label: 'Node.js' },
  { value: 'on-demand-app-development', label: 'On Demand App Development' },
  { value: 'shopify', label: 'Shopify' },
];

export const blogCategorySummery = [
  { value: 'app-development', label: 'App Development' },
  { value: 'dating', label: 'Dating' },
  { value: 'ai', label: 'Artificial Intelligence' },
  { value: 'blockchain', label: 'Blockchain' },
  { value: 'e-commerce', label: 'E-commerce' },
  { value: 'shopify', label: 'Shopify' },
];

export const blogUser = [
  {
    name: 'Veer choudhary',
    image: 'https://av-blog.s3.ap-south-1.amazonaws.com/uploads/veer-gu.jpeg',
    value: 'veer-choudhary',
  },
  {
    name: 'Ashish Bishnoi',
    image:
      'https://av-blog.s3.ap-south-1.amazonaws.com/uploads/ashish-bishnoi.jpeg',
    value: 'ashish-bishnoi',
  },
];
