export const TechonologyData = [
  [
    {
      name: 'React Native',
      imgSrc: '/technologies/react-native.svg',
      content: 'React Native',
      title: 'React Native: Build Cross-Platform Apps Faster',
    },
    {
      name: 'Xamarin',
      imgSrc: '/technologies/xamarin-icon.svg',
      alt: 'Xamarin',
      content: 'Xamarin',
      title: 'Xamarin: Build Cross-Platform Apps with .NET',
    },
    {
      name: 'Ionic',
      imgSrc: '/technologies/Ionic.svg',
      alt: 'Ionic',
      content: 'Ionic',
      title: 'Ionic: Open Source Mobile UI Toolkit',
    },
    {
      name: 'Kotlin',
      imgSrc: '/technologies/kotlin.svg',
      alt: 'Kotlin',
      content: 'Kotlin',
      title: 'Kotlin: Modern Language for Android Development',
    },
    {
      name: 'Flutter',
      imgSrc: '/technologies/flutter.svg',
      alt: 'Flutter',
      content: 'Flutter',
      title: 'Flutter: Build Natively Compiled Apps',
    },
    {
      name: 'Java',
      imgSrc: '/technologies/java.svg',
      alt: 'Java',
      content: 'Java',
      title: 'Java: Reliable and Versatile Programming Language',
    },
    {
      name: 'Xcode',
      imgSrc: '/technologies/xcode.svg',
      alt: 'Xcode',
      content: 'Xcode',
      title: 'Xcode: Apple’s IDE for iOS and macOS Development',
    },
    {
      name: 'Swift',
      imgSrc: '/technologies/swift.svg',
      alt: 'Swift',
      content: 'Swift',
      title: 'Swift: Fast and Safe Programming for Apple Platforms',
    },
  ],

  [
    {
      name: 'JavaScript',
      imgSrc: '/technologies/javascript.svg',
      alt: 'JavaScript',
      content: 'JavaScript',
      width: 50,
      title: 'JavaScript: The Language of the Web',
    },
    {
      name: 'TypeScript',
      imgSrc: '/technologies/typescript.svg',
      alt: 'TypeScript',
      content: 'TypeScript',
      width: 50,
      title: 'TypeScript: JavaScript with Superpowers',
    },
    {
      name: 'React.js',
      imgSrc: '/technologies/react-native.svg',
      alt: 'React.js',
      content: 'React.js',
      title: 'React.js: Build Dynamic User Interfaces',
    },
    {
      name: 'Angular',
      imgSrc: '/technologies/angular-icon.svg',
      alt: 'Angular',
      content: 'Angular',
      title: 'Angular: Framework for Scalable Web Applications',
    },
    {
      name: 'Vue.js',
      imgSrc: '/technologies/vue-js.svg',
      alt: 'Vue.js',
      content: 'Vue.js',
      title: 'Vue.js: The Progressive JavaScript Framework',
    },
    {
      name: 'Bootstrap',
      imgSrc: '/technologies/bootstrap-icon.svg',
      alt: 'Bootstrap',
      content: 'Bootstrap',
      title: 'Bootstrap: CSS Framework for Responsive Design',
    },
    {
      name: 'Material-UI',
      imgSrc: '/technologies/material-ui.svg',
      alt: 'Material-UI',
      content: 'Material-ui',
      title: 'Material-UI: React Components for Material Design',
    },
    {
      name: 'Redux',
      imgSrc: '/technologies/redux.svg',
      alt: 'Redux',
      content: 'Redux',
      title: 'Redux: Predictable State Management',
    },
    {
      name: 'jQuery',
      imgSrc: '/technologies/jquery-icon.svg',
      alt: 'jQuery',
      content: 'Jquery',
      title: 'jQuery: Simplify JavaScript Development',
    },
  ],
  [
    {
      name: 'JavaScript',
      imgSrc: '/technologies/javascript.svg',
      alt: 'Backend',
      content: 'JavaScript',
      title: 'JavaScript: Powering Full-Stack Development',
    },
    {
      name: 'TypeScript',
      imgSrc: '/technologies/typescript.svg',
      alt: 'Backend',
      content: 'TypeScript',
      title: 'TypeScript: Scalable Backend Solutions',
    },
    {
      name: 'Java',
      imgSrc: '/technologies/java.svg',
      alt: 'Backend',
      content: 'Java',
      title: 'Java: Enterprise-Grade Backend Development',
    },
    {
      name: 'Python',
      imgSrc: '/technologies/python.svg',
      alt: 'Backend',
      content: 'Python',
      title: 'Python: Flexible and Versatile Backend Language',
    },
    {
      name: 'PHP',
      imgSrc: '/technologies/php-icon.svg',
      alt: 'Backend',
      content: 'PHP',
      title: 'PHP: The Language of the Web',
    },
    {
      name: 'Node.js',
      imgSrc: '/technologies/node-js.svg',
      alt: 'Backend',
      content: 'Node.js',
      title: 'Node.js: Fast and Scalable Server-Side Platform',
    },
    {
      name: 'Django',
      imgSrc: '/technologies/django.svg',
      alt: 'Backend',
      content: 'Django',
      title: 'Django: The Web Framework for Perfectionists',
    },
    {
      name: 'Laravel',
      imgSrc: '/technologies/laravel.svg',
      alt: 'Backend',
      content: 'Laravel',
      title: 'Laravel: Elegant PHP Framework',
    },
    {
      name: 'MySQL',
      imgSrc: '/technologies/mysql.svg',
      alt: 'Backend',
      content: 'MySQL',
      title: 'MySQL: Reliable Relational Database',
    },
    {
      name: 'MongoDB',
      imgSrc: '/technologies/mongo.svg',
      alt: 'Backend',
      content: 'MongoDB',
      title: 'MongoDB: Flexible NoSQL Database',
    },
  ],

  [
    {
      name: 'TensorFlow',
      imgSrc: '/technologies/tenserflow.svg',
      alt: 'Machine Learning',
      content: 'TensorFlow',
      title: 'TensorFlow: End-to-End Machine Learning Platform',
    },
    {
      name: 'PyTorch',
      imgSrc: '/technologies/pytorch.svg',
      alt: 'Machine Learning',
      content: 'PyTorch',
      title: 'PyTorch: Dynamic Deep Learning Framework',
    },
    {
      name: 'SciKit-Learn',
      imgSrc: '/technologies/scikit-learn.svg',
      alt: 'Machine Learning',
      content: 'SciKit-Learn',
      title: 'SciKit-Learn: Simplifying Machine Learning',
    },
    {
      name: 'Keras',
      imgSrc: '/technologies/Keras.svg',
      alt: 'Machine Learning',
      content: 'Keras',
      title: 'Keras: User-Friendly Deep Learning Framework',
    },
  ],

  [
    {
      name: 'TensorFlow',
      imgSrc: '/technologies/tenserflow.svg',
      alt: 'Machine Learning',
      content: 'TensorFlow',
      title: 'TensorFlow: End-to-End Machine Learning Platform',
    },
    {
      name: 'PyTorch',
      imgSrc: '/technologies/pytorch.svg',
      alt: 'Machine Learning',
      content: 'PyTorch',
      title: 'PyTorch: Dynamic Deep Learning Framework',
    },
    {
      name: 'OpenCV',
      imgSrc: '/technologies/opencv.svg',
      alt: 'Machine Learning',
      content: 'OpenCV',
      title: 'OpenCV: Open Source Computer Vision Library',
    },
    {
      name: 'Keras',
      imgSrc: '/technologies/Keras.svg',
      alt: 'Machine Learning',
      content: 'Keras',
      title: 'Keras: User-Friendly Deep Learning Framework',
    },
  ],

  [
    {
      name: 'Apache Spark',
      imgSrc: '/technologies/spark.svg',
      alt: 'Machine Learning',
      content: 'Apache Spark',
      title: 'Apache Spark: Unified Analytics Engine for Big Data',
    },
    {
      name: 'Hadoop',
      imgSrc: '/technologies/hadoop.svg',
      alt: 'Machine Learning',
      content: 'Hadoop',
      title: 'Hadoop: Framework for Distributed Storage and Processing',
    },
    {
      name: 'Apache Flink',
      imgSrc: '/technologies/flink.png',
      alt: 'Machine Learning',
      content: 'Apache Flink',
      title: 'Apache Flink: Real-Time Stream Processing Framework',
    },
    {
      name: 'Apache Storm',
      imgSrc: '/technologies/storm.svg',
      alt: 'Machine Learning',
      content: 'Apache Storm',
      title: 'Apache Storm: Real-Time Processing System',
    },
    {
      name: 'Apache Kafka',
      imgSrc: '/technologies/kafka.png',
      alt: 'Machine Learning',
      content: 'Apache Kafka',
      title: 'Apache Kafka: Distributed Event Streaming Platform',
    },
  ],

  [
    {
      name: 'Shopify',
      imgSrc: '/technologies/shopify.svg',
      alt: 'Backend',
      content: 'Shopify',
      title: 'Shopify: Build Your Online Store Easily',
    },
    {
      name: 'Magento',
      imgSrc: '/technologies/magento.svg',
      alt: 'Backend',
      content: 'Magento',
      title: 'Magento: Flexible and Scalable E-Commerce Platform',
    },
    {
      name: 'WordPress',
      imgSrc: '/technologies/wordpress.png',
      alt: 'Backend',
      content: 'WordPress',
      title: 'WordPress: The Ultimate CMS for Websites and Blogs',
    },
    {
      name: 'Woo Commerce',
      imgSrc: '/technologies/woocommerce.svg',
      alt: 'Backend',
      content: 'WooCommerce',
      title: 'WooCommerce: E-Commerce for WordPress',
    },
    {
      name: 'Big Commerce',
      imgSrc: '/technologies/bigcommerce.webp',
      alt: 'Backend',
      content: 'Big Commerce',
      title: 'Big Commerce: Enterprise-Grade E-Commerce Platform',
    },
    {
      name: 'Presta Shop',
      imgSrc: '/technologies/prestashop.svg',
      alt: 'Backend',
      content: 'Presta Shop',
      title: 'PrestaShop: Open-Source E-Commerce Platform',
    },
    {
      name: 'Open Kart',
      imgSrc: '/technologies/opencart.svg',
      alt: 'Backend',
      content: 'Open Kart',
      title: 'OpenCart: Free and Open-Source Shopping Cart System',
    },
    {
      name: 'Salesforce Commerce Cloud',
      imgSrc: '/technologies/salesforce.svg',
      alt: 'Backend',
      content: 'Salesforce Commerce Cloud',
      title: 'Salesforce Commerce Cloud: Cloud-Based E-Commerce Solution',
    },
    {
      name: 'React Commerce',
      imgSrc: '/technologies/react-native.svg',
      alt: 'Backend',
      content: 'React Commerce',
      title: 'React Commerce: Dynamic E-Commerce with React',
    },
    {
      name: 'Angular Commerce',
      imgSrc: '/technologies/angular-icon.svg',
      alt: 'Backend',
      content: 'Angular Commerce',
      title: 'Angular Commerce: Build E-Commerce with Angular',
    },
    {
      name: 'Vue StoreFront',
      imgSrc: '/technologies/Vuestorefront.svg',
      alt: 'Backend',
      content: 'Vue StoreFront',
      title: 'Vue Storefront: Headless PWA for E-Commerce',
    },
  ],
];
