import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`bg-[#1c1c1e] text-white antialiased`}>{children}</body> */}
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
